apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: null
  generation: 1
  labels:
    run: anagrams
  name: anagrams
  selfLink: /apis/extensions/v1beta1/namespaces/anagrams/deployments/anagrams
spec:
  replicas: 2
  selector:
    matchLabels:
      run: anagrams
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: anagrams
    spec:
      containers:
      - image: dlalonde/anagrams:v1.11
        imagePullPolicy: Always
        name: anagrams
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
